server:
  servlet:
    context-path: /lookcar

  #单数据源
  #datasource1
spring:
  datasource:
    druid.type: com.alibaba.druid.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xinwodexie113
    #连接池配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    #连接等待超时时间
    max-wait: 30000
    #配置检测可以关闭的空闲连接间隔时间
    time-between-eviction-runs-millis: 60000
    #配置连接在池中的最小生存时间
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #Redis
  redis:
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    password: xinwodexie_113
    timeout: 30000
    ## 连接池中的最大连接数
    redis.poolMaxTotal: 10
    ## 连接池中的最大空闲连接
    redis.poolMaxIdle: 10
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
    redis.poolMaxWait: 3